CREATE DATABASE varshith;
CREATE TABLE admin(
	id INT (25) NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE complain(
	ID INT(25) NOT NULL AUTO_INCREMENT,
    Complaint VARCHAR(255) NOT NULL,
    DATE VARCHAR(30),
    ACTION VARCHAR(255),
    PRIMARY KEY(ID)
);


CREATE TABLE customer(
	ID INT(25) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    Contact VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    Plan VARCHAR(255),
    Sex VARCHAR(255) NOT NULL,
    Purpose VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);


CREATE TABLE employee(
	ID INT(25) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    Contact VARCHAR(255) NOT NULL,
    JoinDate VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    LeaveDate VARCHAR(255),
    PRIMARY KEY(ID)
);


CREATE TABLE plan(
	ID INT(25) NOT NULL,
    PlanName VARCHAR(255) NOT NULL,
    Cost INT (25) NOT NULL,
    Speed VARCHAR(25) NOT NULL,
    Duration VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO admin(username,PASSWORD)
VALUES('admin','pass');